### ISSUE TITLE
dock

### ISSUE THREAD

**Issue by jinyuttt** [Splitwirez/AvaloniaRibbon#13]
I hope to integrate with dock, but it is not successful. Can you help me?
https://github.com/wieslawsoltes/Dock.git

**Comment by Splitwirez** [comment]
Well...what's the problem?

**Comment by jinyuttt** [comment]
I put mainview in the window to display the user control, but it didn't work

**Comment by Splitwirez** [comment]
> 
> 
> I put mainview in the ribbonwindow to display the user control, but it didn't work

Okay, uh...can you show me a screenshot of what *does* happen? Or provide a minimal repro of the problem? Just saying it "didn't work" doesn't really tell me anything about the problem. I need more information if I'm going to help you sort this out.

**Comment by jinyuttt** [comment]
I wanted to show the control, but it didn't. I transplanted the dock sample, but failed to display it.
I have the smallest hope of implementation

![QQ图片20200805013145](https://user-images.githubusercontent.com/13539621/89325521-7fd33d00-d6bb-11ea-9618-8c3d80457d77.png)

**Comment by Splitwirez** [comment]
> 
> 
> I wanted to show the control, but it didn't. I transplanted the dock sample, but failed to display it.
> I have the smallest hope of implementation
> 
> ![QQ图片20200805013145](https://user-images.githubusercontent.com/13539621/89325521-7fd33d00-d6bb-11ea-9618-8c3d80457d77.png)

Hmm...have you added

```xml
<StyleInclude Source="avares://AvaloniaUI.Ribbon/Styles/RibbonStyles.xaml" />
```
to your `App.xaml`'s `Styles`?

**Comment by jinyuttt** [comment]
yes

**Comment by Splitwirez** [comment]
Okay...I think I may need more context. Is the app you're working on available on GitHub or something?

**Comment by jinyuttt** [comment]
Yes, but I'm afraid you may have some difficulties. Many of the notes and texts are in Chinese..
https://github.com/jinyuttt/PlatApplication.git

**Comment by Splitwirez** [comment]
Okay, so I've built your program, and...I think I may have misunderstood the problem. I thought you said the _entire Ribbon_ didn't show up, but the only thing that's not showing up here is the text - I'm just seeing boxes instead of Chinese characters. Is that the problem you were experiencing?

**Comment by jinyuttt** [comment]
I added a test panel (the last one) and added a button. I have two questions:

1. The button feels very small.

2. Through the button event, you want to load the fileview interface into the dock (or mainview). But it can't be shown. I don't know if it's the ribbon wide effect.

**Comment by jinyuttt** [comment]
Chinese “测试” mean  "test”

**Comment by jinyuttt** [comment]
？？？
