### ISSUE TITLE
Target .NET Standard or .NET Core

### ISSUE THREAD

**Issue by waliarubal** [Splitwirez/AvaloniaRibbon#14]
I am getting below warning in project Jaya which targets .NET Core 3.1. Please fix targeted framework for the package on nuGet.

warning NU1701: Package 'AvaloniaUIRibbon 1.0.5-beta' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

**Comment by viniciusmiguel** [comment]
Please remove the full framework dependency.

**Comment by Splitwirez** [comment]
> Please remove the full framework dependency.

There actually is no full framework dependency, I just screwed up the NuGet information.

...note to self: Fix that for the next release.

**Comment by Splitwirez** [comment]
Done and done.
