### ISSUE TITLE
RibbonWindow

### ISSUE THREAD

**Issue by jinyuttt** [Splitwirez/AvaloniaRibbon#16]
When Dock is used with ribbonwindow, Dock cannot receive mouse events correctly.

https://github.com/jinyuttt/PlatApplication.git 

https://github.com/jinyuttt/PlatApplication/pull/2

https://github.com/wieslawsoltes/Dock/issues/168

**Comment by Splitwirez** [comment]
Thanks for the heads-up on this. I've reached out to this Dock project to try to learn more about the problem, in the hopes that I'll then be able to fix it. Sorry for the inconvenience.

**Comment by jinyuttt** [comment]
@Splitwirez  Thank you for your efforts. I got a lot of things.

**Comment by jinyuttt** [comment]
??
