### ISSUE TITLE
Add SplitButton

### ISSUE THREAD

**Issue by robloo** [Splitwirez/AvaloniaRibbon#18]
This project could benefit from a [SplitButton](https://github.com/AvaloniaUI/Avalonia/issues/4959) when it's added to Avalonia itself. It looks like this functionality is currently disabled: https://github.com/Splitwirez/AvaloniaRibbon/blob/master/AvaloniaUI.Ribbon/RibbonSplitButton.cs

![image](https://user-images.githubusercontent.com/17993847/102854963-b05d0e80-43f1-11eb-8601-4226a093124b.png)

From WPF: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.ribbon.ribbonsplitbutton?view=net-5.0

**Comment by Splitwirez** [comment]
Sorry for the late reply.

The SplitButton is not disabled - what you see commented out in that file is an unsuccessful previous attempt at implementing a SplitButton.
