### ISSUE TITLE
Disabling the Titlebar

### ISSUE THREAD

**Issue by seljmov** [Splitwirez/AvaloniaRibbon#20]
Hi!
I don't use "RibbonContextualTabGroup" and other controls that use titlebar. Can I disable the titlebar?
![Titlebar](https://user-images.githubusercontent.com/56289147/107149299-e6862b80-6968-11eb-80c2-5c146992f400.jpg)

**Comment by Splitwirez** [comment]
Currently, no...guess I'll add that to the list of things to change.

**Comment by seljmov** [comment]
@Splitwirez Okey, thanks you!
