### ISSUE TITLE
update Avalonia

### ISSUE THREAD

**Issue by jinyuttt** [Splitwirez/AvaloniaRibbon#21]
Avalonia 0.10?

**Comment by seljmov** [comment]
@jinyuttt Hi! Check develop-branch, she is work on avalonia 10.0.
https://github.com/Splitwirez/AvaloniaRibbon/tree/develop

You can download develop-branch and add it to yourself as a project.

**Comment by Splitwirez** [comment]
Done and done. Avalonia 0.10.0-compatible update went up to nuget yesterday.

**Comment by seljmov** [comment]
Great, good job @Splitwirez
