### ISSUE TITLE
Make GalleryItem clickable

### ISSUE THREAD

**Issue by furesoft** [Splitwirez/AvaloniaRibbon#22]

**Comment by Splitwirez** [comment]
Care to elaborate on what exactly is wrong?

**Comment by furesoft** [comment]
The Sample Ribbon Galleryitems are not clickable

**Comment by Splitwirez** [comment]
I see what you mean now. This is now resolved on the https://github.com/Splitwirez/AvaloniaRibbon/tree/develop branch. Thanks.
