### ISSUE TITLE
AvaloniaRibbon repo

### ISSUE THREAD

**Issue by jinyuttt** [Splitwirez/AvaloniaRibbon#38]
At present, the original authors do not have the energy to maintain it, or to switch to other directions. I hope that someone will continue to be interested in it (at least come to GitHub), maintain its updates and communication, please leave the repository address, and we will unify it. Is that okay?

We strive to complete it before March 15, 2024.

**Comment by Splitwirez** [comment]
https://github.com/Splitwirez/AvaloniaRibbon/pull/37

**Comment by jinyuttt** [comment]
ok
