### ISSUE TITLE
Standalone control

### ISSUE THREAD

**Issue by jinyuttt** [Splitwirez/AvaloniaRibbon#5]
1.It is suggested to change the name,Ribbon to ribboncontrol;

2.Modify the namespace, do not mix with Avalonia, take a separate name

**Comment by Splitwirez** [comment]
1. Oh? Why is that?

2. Yeah, I've changed the namespace now. My bad.

**Comment by jinyuttt** [comment]
@Splitwirez There's no problem. It's just that the name of all similar controls on the windows platform is called ribboncontrol, which is more in line with the habit of windows components.

**Comment by jinyuttt** [comment]
Please update Avalonia 0.9.10. I created an Avalonia project according to your example. My project was unsuccessful.
The titlebarbackground is not recognized.
![20200701174601](https://user-images.githubusercontent.com/13539621/86229837-dc29d500-bbc2-11ea-8fab-a3f07e3a0f4c.png)

**Comment by jinyuttt** [comment]
Have you ever used devexprress?

Can a matching ribbon state bar be produced?

**Comment by jinyuttt** [comment]
How to put the title of ribbon window in the middle and enlarge the font? I want to put the logo in the upper left corner of the window (the current title position). How to operate?How to put the title of ribbon window in the middle and enlarge the font? I want to put the logo in the upper left corner of the window (the current title position). How to operate?

**Comment by Splitwirez** [comment]
> @Splitwirez There's no problem. It's just that the name of all similar controls on the windows platform is called ribboncontrol, which is more in line with the habit of windows components.

Hm...I guess I could rename the actual `Ribbon` control itself, if that's what you mean.


> Please update Avalonia 0.9.10

Currently discussing updating to Avalonia 0.9.11, is that acceptable?




> Have you ever used devexprress?

No, no I have not.


> Can a matching ribbon state bar be produced?

Um...I can't find a control by that name. Did you mean a ribbon *status* bar?


> How to put the title of ribbon window in the middle and enlarge the font? I want to put the logo in the upper left corner of the window (the current title position). How to operate?

I'll do you one better, and properly support the existing `Icon` property.

**Comment by jinyuttt** [comment]
Thank you very much. You are right. I feel that you are right. There is no need to modify it. Of course, you can update to the latest version of Avalonia;

That's what you call the status bar;

Thank you. The control I am studying and using to do demo may be used in production environment.

**Comment by jinyuttt** [comment]
@Splitwirez Hello, do you have time to implement statusbar recently?

**Comment by Splitwirez** [comment]
> 
> 
> @Splitwirez Hello, do you have time to implement statusbar recently?

Could you elaborate on the exact functionality you want, and what it has to do with the Ribbon?

**Comment by jinyuttt** [comment]
It is the status bar in WPF, which can adapt to skin, and can add various kinds of controls, and the controls are obviously separated (|). Generally, labels, buttons and text boxes are allowed to be added. Set left or right.
