### ISSUE TITLE
Ribbon Tab Group Header Misalign

### ISSUE THREAD

**Issue by waliarubal** [Splitwirez/AvaloniaRibbon#7]
Ribbon tab group headers should be centered aligned but for some reason they are more inclined towards bottom-left edge instead of being towards bottom-center. See screenshot below.

![bug](https://user-images.githubusercontent.com/20422731/86435976-e2cd5f00-bd1e-11ea-986a-172ad12d075a.png)

**Comment by Splitwirez** [comment]
Fixed. Fix also ported to Jaya-specific styles.
