### ISSUE TITLE
Menu Title Missing for Primary Menu

### ISSUE THREAD

**Issue by waliarubal** [Splitwirez/AvaloniaRibbon#9]
Menu title is missing for primary menu of ribbon which appears before first ribbon tab. Not sure if its a ribbon issue or you have left it in JayaFM. If left in JayaFM then you may fix it in that repo. See screenshot below.

![image](https://user-images.githubusercontent.com/20422731/86436695-66d41680-bd20-11ea-903e-63fc55fbbf2b.png)

**Comment by Splitwirez** [comment]
Yeah, this was specific to Jaya. Fixed there.
